name: now-postprocess
channels:
  - conda-forge
dependencies:
  - python>=3.6
  - jupyterlab
  - nb_conda 
  - xarray
  - pandas
  - dask
  - dask-jobqueue
  - netcdf4
  - zarr
  - numpy
  - scipy
  - wrf-python
  - xgcm
  - matplotlib
  - cartopy
  - seaborn
  - cmocean
  - colorcet
